### ISSUE TITLE
Wrong field parameter for Brainpool-p224t1

### ISSUE THREAD

**Issue by lukbettale** [cslashm/ECPy#19]
Error:
`ecpy.curves.Curve.get_curve('Brainpool-p224t1')`
raises an error (`ECPyException("Point not on curve")` for the generator).

The field parameter for this curve is wrong. It should be corrected to
`0xD7C134AA264366862A18302575D1D787B09F075797DA89F57EC8C0FF`

**Comment by cslashm** [comment]
Thanks for reporting I check that!

**Comment by cslashm** [comment]
fix in 1.2.5
