### ISSUE TITLE
multiplication by 0 not working well in secp256k1

### ISSUE THREAD

**Issue by avivz** [cslashm/ECPy#6]
So, I was trying to use your library to do some additive homomorphic stuff (vector commitments for bulletproofs using secp256k1 more specifically). I then encountered some trouble:

Running the following:
```
from ecpy.curves import Curve
C = Curve.get_curve("secp256k1")
G = C.generator
((0*G) + (0*G)) == `(0*G)
```
the last statement is 'False'
mostly because
```0*G == G```

Similarly `G-G` gives an object with an invalid state that can't be printed.

**Comment by cslashm** [comment]
Thanks for reporting. 

Indeed infinite point (with  ø = 0.P, &#x2200; P &#x2208; Curve) seems not correctly handle. 
I look at that quickly

**Comment by cslashm** [comment]
Added a infinity point management in 1.0.0beta
